services:
  youtube-notifier:
    # build: .
    image: ghcr.io/codefaux/ytdlp-telegram-filter-notifier:latest
    container_name: ytdlp_notifier
    restart: unless-stopped
    volumes:
      - ./data:/data
    # command: ["python", "ytdlp-filter-notify.py", "run", "--suppress-skip-msgs", "--data-dir", "/data", "--interval-hours", "1"]
